[sources.docker]
type = "docker_logs"

[transforms.json]
type = "remap"
inputs = ["docker"]
source = '''
structured = parse_json!(.message)
'''

[sinks.loki]
type = "loki"
inputs = ["json"]
endpoint = "http://loki:3100"
encoding.codec = "json"
labels.container = "{{ container_name }}"
labels.service = "{{ structured.service }}"
